### ISSUE TITLE
Python version conflict

### ISSUE THREAD

**Issue by sunny1226** [asarnow/pyem#32] opened 2019-06-27 01:01 UTC
I notice that pyem have an update and gonna to install the latest version. However, it said that Python version >= 3.5 required. but in the wiki, not only the pip command but also Miniconda tell us we need use python2. When I use python3's pip to install the software, it also cannot open. that make me so confuse. Which python should I indeed use for pyem?

**Comment by asarnow** [comment] 2019-07-11 18:50
I developed against Python 2.7, but I've done a few passes for Python 3.6 compatibility. It should work in either version, but Python 3 support can be considered experimental. Over the next couple of weeks I'll be updating the installation instructions (to use conda) and making Python 3 the main supported version.

**Comment by asarnow** [comment] 2019-09-27 23:41
Python 3.7+ is the officially supported Python version now. Any related bugs should go into their own issues; anything caused by Python < 3.7 will be fixed only if there is an easy, version-neutral approach.

**Closed by asarnow** 2019-09-27 23:41 UTC
Labels: enhancement
