### ISSUE TITLE
TypeError in csparc2star.py

### ISSUE THREAD

**Issue by attamatti** [asarnow/pyem#28] opened 2019-01-31 11:50 UTC
I get the following error when running csparc2star.py:

  File "csparc2star.py", line 103, in <module>
    sys.exit(main(parser.parse_args()))
  File "csparc2star.py", line 42, in main
    df = metadata.parse_cryosparc_2_cs(cs, passthrough=args.passthrough, minphic=args.minphic)
  File "/usr/lib/python3.5/site-packages/pyem/metadata.py", line 313, in parse_cryosparc_2_cs
    star.simplify_star_ucsf(df)
  File "/usr/lib/python3.5/site-packages/pyem/star.py", line 364, in simplify_star_ucsf
    lambda x: "%.6d" % (x + 1)).str.cat(df[UCSF.IMAGE_PATH], sep="@")
  File "/usr/lib64/python3.5/site-packages/pandas/core/strings.py", line 2320, in cat
    res = str_cat(data, others=others, sep=sep, na_rep=na_rep)
  File "/usr/lib64/python3.5/site-packages/pandas/core/strings.py", line 110, in str_cat
    cats = [sep.join(tup) for tup in tuples]
  File "/usr/lib64/python3.5/site-packages/pandas/core/strings.py", line 110, in <listcomp>
    cats = [sep.join(tup) for tup in tuples]
TypeError: sequence item 1: expected str instance, bytes found

**Comment by asarnow** [comment] 2019-02-02 07:57
Hi, thanks for trying my software.

This is a duplicate of #19. It's caused by using Python 3 instead of Python 2.7.  While it should be fixed in the latest pyem release (tag v0.4), pyem is only guaranteed to work with Python 2.7. You should allow the pyem scripts to choose their Python interpreter by executing them directly (`./foo.py` NOT`python foo.py`).

**Closed by asarnow** 2019-02-02 07:57 UTC
