### ISSUE TITLE
Running new recenter.py

### ISSUE THREAD

**Issue by Rafael-Ayala** [asarnow/pyem#6] opened 2017-09-12 13:39 UTC
Hi,

I have recently been attempting to run recenter.py (looks very handy with all the centring modes implemented now!). However, I have not been able to succesfully do so, and I am wondering if you could possibly provide an example of intended usage? I gave it a shot at centring based on 2D classes in the following way:

recenter.py --class-2d Class2D/mrcs_stack_with_2Dclasses.mrcs Class2D/data_star_file_with_rlnClassNumber.star test_recenter.star

Then got an error along the lines of   

File "/csbdatalocal/ra3014/pyem/recenter.py", line 47, in main
    com = Vec2f(*im.phase_cog()[:2])
NameError: global name 'Vec2f' is not defined

Which I got around by adding Vec2f to the imports from EMAN2. But now Im getting the following 

Traceback (most recent call last):
  File "/csbdatalocal/ra3014/pyem/recenter.py", line 104, in <module>
    sys.exit(main(args))
  File "/csbdatalocal/ra3014/pyem/recenter.py", line 57, in main
    for ptcl in star.rows:
  File "/csb/home/ra3014/anaconda2/lib/python2.7/site-packages/pandas/core/generic.py", line 2744, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'rows'

Any help would be appreciated! Thanks a lot in advance!

**Comment by asarnow** [comment] 2017-10-03 07:08
Sorry to disappoint you, Rafael, but I haven't finished this code yet. I'll try and pick it up again soon, next week maybe.

**Comment by asarnow** [comment] 2018-03-22 07:26
Duplicate of #1

**Closed by asarnow** 2018-03-22 07:26 UTC
