### ISSUE TITLE
metadata.py breaks with particles with 2D and 3D pose

### ISSUE THREAD

**Issue by brisvag** [asarnow/pyem#67] opened 2021-06-11 09:57 UTC
If one runs:
```
pyem.metadata.parse_cryosparc_2_cs(data)
```
when `data` contains both `alignments3D/pose` and `alignments2D/pose`, the code breaks here: https://github.com/asarnow/pyem/blob/ed0527f98657d21d887357426b74e5240d477fae/pyem/metadata.py#L334-L335

This seems to be caused by the fact that it's trying to put everything in a big numpy array, which fails due to the different dimensionality of the 2 values (1 angle vs a list of 3 angles).

I tried some dumb fixes, but everything failed... it's too deep in the weeds of the code for me.

**Comment by asarnow** [comment] 2021-07-30 00:28
Is the stack trace the "columns must be same length as key" error?

**Comment by brisvag** [comment] 2021-07-30 09:40
Yes, that one! Sorry, I forgot to add the trace.

**Comment by asarnow** [comment] 2021-07-30 19:11
Thanks. My numpy recarray-to-DataFrame converter is low-level so it's fast but brittle. An alternative solution shouldn't be too hard to come up with... Duplicate of #59

**Closed by asarnow** 2021-07-30 19:11 UTC

**Comment by yizengem** [comment] 2021-09-26 23:16
I have a tentative fix for this error which separates alignments3D/pose from alignments2D/pose within the recarray prior to appending to the data frame. This will lose the alignments2D/pose information (1 angle as brisvag has pointed out) in favour of the 3D angular information (3 values). This was sufficient for our exported particles from CS into Relion for additional ab initio, 3D classification and 3D refinement.

```--- metadata.py    2021-09-18 14:05:55.000000000 +1000
+++ metadata_edited.py    2021-09-18 13:01:43.000000000 +1000
@@ -331,8 +331,10 @@
         for k in model:
             if model[k] is not None:
                 names = [n for n in cs.dtype.names if n.endswith(k)]
-                    df[model[k]] = pd.DataFrame(np.array(
-                        [cs[names[c]][i] for i, c in enumerate(cls)]))
+                if "alignments3D/pose" in names:
+                    df[model['pose']] = pd.DataFrame(np.array([cs['alignments3D/pose'][i] for i, c in enumerate(cls)]))
+                else:
+                    df[model[k]] = pd.DataFrame(np.array([cs[names[c]][i] for i, c in enumerate(cls)]))
         if minphic > 0:
             df.drop(df.loc[cls_prob < minphic].index, inplace=True)
     elif len(phic_names) == 1:```
